#!/usr/bin/python3

# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2020 Ericsson AB

import random
import select
import sys
import time

import paf.client as client


def usage(name):
    print("%s <num-services> <num-subscriptions> <addr>" % name)


def wait_for(conn, criteria):
    poll = select.poll()
    poll.register(conn.fileno(), select.EPOLLIN)
    while not criteria():
        poll.poll()
        conn.process()


class EventCounter:
    def __init__(self, event_type, target):
        self.target = target
        self.event_type = event_type
        self.events = []

    def __call__(self, ta_id, event_type, *args, **optargs):
        if self.event_type == event_type:
            self.events.append(args)

    def done(self):
        return len(self.events) == self.target


MAX_BATCH_SIZE = 1024


def batch_op(count, op, done_event):
    completed = 0
    while completed < count:
        left = count - completed
        batch_size = min(MAX_BATCH_SIZE, left)

        counter = EventCounter(done_event, batch_size)

        for i in range(batch_size):
            op(completed + i, counter)

        wait_for(conn, counter.done)

        completed += batch_size


def subscribe(conn, subscription_ids):
    def subscribe_op(i, cb):
        conn.subscribe(subscription_ids[i], cb, filter="(name=service-%d)" % i)
    batch_op(len(subscription_ids), subscribe_op, client.EventType.ACCEPT)


def unsubscribe(conn, subscription_ids):
    def unsubscribe_op(i, cb):
        conn.unsubscribe(subscription_ids[i], cb)
    batch_op(len(subscription_ids), unsubscribe_op, client.EventType.COMPLETE)


def publish(conn, service_ids):
    ttl = 1
    generation = 0

    def publish_op(i, cb):
        service_id = service_ids[i]
        conn.publish(service_id, generation, {
            "name": {"service-%d" % i},
            "addr": {"tls:10.10.10.10:4711"},
            "color": {"green"}
        }, ttl, cb)

    batch_op(len(service_ids), publish_op, client.EventType.COMPLETE)


def unpublish(conn, service_ids):
    def unpublish_op(i, cb):
        conn.unpublish(service_ids[i], cb)
    batch_op(len(service_ids), unpublish_op, client.EventType.COMPLETE)


def ping(conn, count):
    def ping_op(i, cb):
        conn.ping(cb)
    batch_op(count, ping_op, client.EventType.COMPLETE)


def pre_populate(conn, service_ids, subscriptions_ids):
    subscribe(conn, subscriptions_ids)
    publish(conn, service_ids)


def cleanup(conn, service_ids):
    unpublish(conn, service_ids)


def generate_ids(num):
    return [random.randint(0, 9223372036854775807) for _ in range(num)]


TEST_ITER = 16


def benchmark_publish_unpublish(conn, num_services, num_subscriptions):
    pre_service_ids = generate_ids(num_services)
    pre_subscription_ids = generate_ids(num_subscriptions)

    print("Pathfinder pre-populated state")
    print("------------------------------")
    print("Services: %d" % num_services)
    print("Subscriptions: %d" % num_subscriptions)

    pre_populate(conn, pre_service_ids, pre_subscription_ids)

    service_ids = generate_ids(TEST_ITER)
    subscription_ids = generate_ids(TEST_ITER)

    print("\nResults")
    print("-------")

    start = time.time()
    subscribe(conn, subscription_ids)
    latency = time.time() - start

    print("Subscribe: %.3f ms/op" % (1000*(latency/TEST_ITER)))

    start = time.time()
    unsubscribe(conn, subscription_ids)
    latency = time.time() - start

    print("Unsubscribe: %.3f ms/op" % (1000*(latency/TEST_ITER)))

    start = time.time()
    publish(conn, service_ids)
    latency = time.time() - start

    print("Publish: %.3f ms/op" % (1000*(latency/TEST_ITER)))

    start = time.time()
    unpublish(conn, service_ids)
    latency = time.time() - start

    print("Unpublish: %.3f ms/op" % (1000*(latency/TEST_ITER)))

    start = time.time()
    ping(conn, TEST_ITER)
    latency = time.time() - start

    print("Ping: %.3f ms/op" % (1000*(latency/TEST_ITER)))

    cleanup(conn, pre_service_ids)

if len(sys.argv) != 4:
    usage(sys.argv[0])
    sys.exit(1)

num_services = int(sys.argv[1])
num_subscriptions = int(sys.argv[2])
addr = sys.argv[3]

conn = client.connect(addr)
benchmark_publish_unpublish(conn, num_services, num_subscriptions)
conn.close()
