@startuml

participant "App A" as app_a << App >>
participant "Lib A" as lib_a << PAF Library >>
participant "Socket A" as sock_a << XCM Connection Socket >>

participant "Server" as server << PAF Server >>

participant "Socket B" as sock_b << XCM Connection Socket >>
participant "Lib B" as lib_b << PAF Library >>
participant "App B" as app_b << App >>

app_a -> lib_a: Create Context
app_a -> lib_a: Publish 0x4711 {'name': 'foo'}
lib_a -> sock_a: Connect
sock_a -> server: Establish TLS/TCP
lib_a -> server: Protocol Hello
lib_a -> server: Protocol Publish 0x4711 {'name': 'foo'}

app_b -> lib_b: Create Context
lib_b -> sock_b: Connect
sock_b -> server: Establish TLS/TCP
lib_b -> server: Protocol Hello
app_b -> lib_b: Subscribe (name=foo)
lib_b -> server: Protocol Subscribe (name=foo)
server -> lib_b: Protocol Match: Appeared: 0x4711 {'name': 'foo'}
lib_b -> app_b: Match Callback: Appeared: 0x4711 {'name': 'foo'}
...
sock_a <-> server: Network Connectivity Lost
...
sock_a -> lib_a: Connection Timed Out/Reset
lib_a -> lib_a: Install Retry Timer (250 ms)
server -> server: Lost Client A
server -> lib_b: Protocol Match: Modified: 0x4711 {'name': 'foo'}\nOrphan Since: <Now>
...
lib_a -> sock_a: Connect
sock_a -> lib_a: Network is Unreachable
...
lib_a -> sock_a: Connect
sock_a -> server: Establish TLS/TCP
lib_a -> server: Protocol Hello
lib_a -> server: Protocol Publish 0x4711 {'name': 'foo'}
server -> lib_b: Protocol Match: Modified: 0x4711 {'name': 'foo'}\n[Not Orphan]

@enduml


